### ISSUE TITLE
Create a organization

### ISSUE THREAD

**Issue by tuzu128** [mellow-theme/mellow.nvim#17]
I suggest moving mellow.nvim into organization for Mellow theme. This would make porting apps to Mellow easier and it would make finding ports easier.

**Comment by kvrohit** [comment]
That's a great idea. I created an org here: https://github.com/mellow-theme. But the existing theme installs might start breaking if I move this repo under that org. Does any solution come in mind?

**Comment by tuzu128** [comment]
Sorry for the late response. I would suggest adding disclaimer into readme and probably into the theme it self using vim.print on startup. I would have the theme in both the organization and here for some time and then move into the organization completely.

**Comment by tuzu128** [comment]
I created pull request for the warnings #18

**Comment by kvrohit** [comment]
> Sorry for the late response. I would suggest adding disclaimer into readme and probably into the theme it self using vim.print on startup. I would have the theme in both the organization and here for some time and then move into the organization completely. Also I think that if the user alredy has the theme installed, it will stay localy on their machine until they remove it.

Github also supports automatic redirects after the repo move so it should mostly work.
