### ISSUE TITLE
Mellow notification

### ISSUE THREAD

**Issue by AxewBoTX** [mellow-theme/mellow.nvim#19]
whenever I open neovim, for some reason it always says
`Mellow.nvim has moved to mellow-theme/mellow.nvim`
how to get rid of this?

**Comment by AxewBoTX** [comment]
![Screenshot 2023-12-29 131501](https://github.com/mellow-theme/mellow.nvim/assets/84615670/9d9eba36-f3d0-454a-aa54-337fb7722939)

**Comment by AxewBoTX** [comment]
I found the line that does this
it's [this](https://github.com/mellow-theme/mellow.nvim/blob/716a0a70563b8b986b910e7a51f60c424fee01bc/lua/mellow/init.lua#L314) line but, I don't get why is it even in the code?

**Comment by kvrohit** [comment]
Yeah, I recently moved this under the mellow-theme org and it was a way to notify users of the change. There is probably a better way to do it though. For now I have reverted that change. Please update the plugin and it should be gone.

**Comment by AxewBoTX** [comment]
thanks brother
