### ISSUE TITLE
Can you add your iTerm2 to the main colorscheme repository?

### ISSUE THREAD

**Issue by arthsmn** [mellow-theme/mellow.nvim#28]
As you have an iTerm2 port, I would like to request you to add it [here](https://github.com/mbadolato/iTerm2-Color-Schemes). The reason is that Ghostty use schemes from this repository, and automatically adds them so they can be called. This would make a port uneeded. Also, this repository converts the colorscheme to a variety of tools (some of which are not yet available). You can also adopt the conversion and just write one theme, as most of the terminals and apps are available.

**Comment by OlshaMB** [comment]
@arthsmn @kvrohit made a pr https://github.com/mbadolato/iTerm2-Color-Schemes/pull/453

**Comment by OlshaMB** [comment]
@arthsmn The pr is closed.
<details><summary>Shameless request</summary>
<p>
Also any chance you could get me ghostty. I've been waiting for months.
</p>
</details>

**Comment by OlshaMB** [comment]
@kvrohit Any chance we could remove themes included in iterm color schemes?
