### ISSUE TITLE
No syntax highlighting for Markdown when Treesitter is enabled.

### ISSUE THREAD

**Issue by adam12** [mellow-theme/mellow.nvim#30]
I _think_ this used to work, and I don't know of anything in my configuration that might have changed anything, other than perhaps a Treesitter update.

If I disable Treesitter on a Markdown buffer, the syntax highlighting is working correctly.

If I run this command on the open buffer when Treesitter is enabled, I get back this list of captures.

```
:lua =vim.treesitter.highlighter.active[vim.api.nvim_get_current_buf()]
```

```
captures = <2>{ "markup.heading.1", "markup.heading.1.marker", "markup.heading.2", "markup.heading.2.marker", "markup.heading.3.marker", "ma
rkup.heading.3", "markup.heading.4.marker", "markup.heading.4", "markup.heading.5.marker", "markup.heading.5", "markup.heading.6.marker", "markup.he
ading.6", "label", "markup.heading", "punctuation.special", "markup.raw.block", "markup.raw.delimiter", "conceal", "markup.link.url", "markup.link.l
abel", "markup.list", "markup.list.unchecked", "markup.list.checked", "markup.quote", "string.escape", "spell" },
```

I'm not sure if that means anything, tho I did find another theme with similar highlights defined for them:

https://github.com/bluz71/vim-moonfly-colors/blob/a1a0dfc621f41ffb4e98a813e021ba41e8199adc/lua/moonfly/init.lua#L443-L463

I noticed there are no similar highlights in Mellow. Perhaps the issue?

NVIM v0.9.5
`:checkhealth` shows no issues

**Comment by kvrohit** [comment]
Hi there! Thanks for reporting this issue with links to other implementations. Will try and address it soon.
